// src/lib/agentRoster.js
// Single source of truth for the 6-agent Transit Map station graph.
// Explains the exact CockroachDB operation executed by every agent node.

export const AGENT_ROSTER = [
  {
    key: "ingest",
    name: "Iris",
    role: "Ingest",
    icon: "📥",
    index: 0,
    readOnly: false,
    parallel: false,
    tag: "Single-Writer",
    crdbOp: "Managed MCP: INSERT incident & initial lock rows",
    crdbDetails: "Creates the primary incident record and lock lease in CockroachDB using Managed MCP Server.",
    shortDesc: "Dedupes on fingerprint, creates incident + lock rows first so downstream never races on missing foreign keys.",
    desk: { x: 80, y: 150 },
  },
  {
    key: "triage",
    name: "Theo",
    role: "Triage",
    icon: "🩺",
    index: 1,
    readOnly: true,
    parallel: true,
    tag: "Read-Only Parallel",
    crdbOp: "Managed MCP: SELECT prior fingerprint history",
    crdbDetails: "Queries CockroachDB for historical incident patterns sharing the exact payload fingerprint.",
    shortDesc: "Queries CockroachDB for historical incident patterns sharing the exact payload fingerprint.",
    desk: { x: 260, y: 80 },
  },
  {
    key: "runbook",
    name: "Remy",
    role: "Runbook",
    icon: "📚",
    index: 2,
    readOnly: true,
    parallel: true,
    tag: "Read-Only Parallel",
    crdbOp: "Direct SQL: 384-dim Vector Search over postmortems",
    crdbDetails: "Executes cosine distance search against fastembed ONNX vector embeddings stored in CockroachDB.",
    shortDesc: "Performs vector embedding search over runbooks & past postmortems in parallel with Triage.",
    desk: { x: 260, y: 220 },
  },
  {
    key: "merge",
    name: "Mira",
    role: "Merge",
    icon: "🔀",
    index: 3,
    readOnly: false,
    parallel: false,
    tag: "Superstep Interchange",
    crdbOp: "Direct SQL: UPDATE status transition (Pregel superstep)",
    crdbDetails: "Pregel superstep join updates incident status in CockroachDB once Triage & Runbook complete.",
    shortDesc: "Single status transition point. LangGraph Pregel guarantees Merge executes after both Triage & Runbook finish.",
    desk: { x: 460, y: 150 },
  },
  {
    key: "remediation",
    name: "Ash",
    role: "Remediation",
    icon: "🛠️",
    index: 4,
    readOnly: false,
    parallel: false,
    tag: "Lock-Acquiring",
    crdbOp: "Direct SQL: Acquire/Steal 20s Lease Lock",
    crdbDetails: "Acquires or steals distributed lock in CockroachDB using serializable UPDATE transactions.",
    shortDesc: "Acquires CockroachDB distributed lock; steals expired lease if peer region dies mid-execution.",
    desk: { x: 660, y: 150 },
  },
  {
    key: "postmortem",
    name: "Nova",
    role: "Postmortem",
    icon: "📓",
    index: 5,
    readOnly: false,
    parallel: false,
    tag: "Feedback Loop",
    crdbOp: "Managed MCP: INSERT vector postmortem document",
    crdbDetails: "Writes final AI-synthesized postmortem back to CockroachDB to expand future vector search corpus.",
    shortDesc: "Generates embedded incident report back into CockroachDB, expanding Runbook's future search vector corpus.",
    desk: { x: 850, y: 150 },
  },
];

export const COCKROACHDB_STATION = {
  key: "cockroachdb",
  name: "CockroachDB",
  role: "Shared Memory Core",
  icon: "🪳",
  shortDesc: "Stateless compute interchange. The single durable source of truth for both regional line services.",
};

export const FLOW_EDGES = [
  ["ingest", "triage"],
  ["ingest", "runbook"],
  ["triage", "merge"],
  ["runbook", "merge"],
  ["merge", "remediation"],
  ["remediation", "postmortem"],
];

export const STAGE_EVENTS = {
  ingest:      { started: [], done: ["incident_created", "incident_retriggered"] },
  triage:      { started: ["triage_started"], done: ["triage_completed"] },
  runbook:     { started: ["runbook_started"], done: ["runbook_completed"] },
  merge:       { started: [], done: ["context_merged"] },
  remediation: { started: ["remediation_lock_attempt"],
                 done: ["remediation_applied", "remediation_completed", "remediation_stood_down"] },
  postmortem:  { started: ["postmortem_started"], done: ["postmortem_written"] },
};
