version = 0.1

[default.deploy.parameters]
stack_name = "cortex-us-east-1"
resolve_s3 = true
s3_prefix = "cortex-us-east-1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GroqApiKeyParam=\"/cortex/groq_api_key\" CrdbHostParam=\"/cortex/crdb_host\" TriageAgentPasswordParam=\"/cortex/triage_agent_password\" RunbookAgentPasswordParam=\"/cortex/runbook_agent_password\" RemediationAgentPasswordParam=\"/cortex/remediation_agent_password\" PostmortemAgentPasswordParam=\"/cortex/postmortem_agent_password\" CrdbClusterIdParam=\"/cortex/crdb_cluster_id\" CrdbMcpApiKeyParam=\"/cortex/crdb_mcp_api_key\" CrdbMcpEndpointParam=\"/cortex/crdb_mcp_endpoint\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"

[west.deploy.parameters]
stack_name = "cortex-us-west-2"
resolve_s3 = true
s3_prefix = "cortex-us-west-2"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GroqApiKeyParam=\"/cortex/groq_api_key\" CrdbHostParam=\"/cortex/crdb_host\" TriageAgentPasswordParam=\"/cortex/triage_agent_password\" RunbookAgentPasswordParam=\"/cortex/runbook_agent_password\" RemediationAgentPasswordParam=\"/cortex/remediation_agent_password\" PostmortemAgentPasswordParam=\"/cortex/postmortem_agent_password\" CrdbClusterIdParam=\"/cortex/crdb_cluster_id\" CrdbMcpApiKeyParam=\"/cortex/crdb_mcp_api_key\" CrdbMcpEndpointParam=\"/cortex/crdb_mcp_endpoint\""
image_repositories = []

[west.global.parameters]
region = "us-west-2"
