"""
One-time re-embedding pass: regenerates every stored runbook/postmortem
embedding using fastembed (ONNX runtime) instead of the original
sentence-transformers/torch pipeline.

Run this ONCE, locally, before pointing the deployed Lambda at fastembed.
Mixing vectors from two different generation methods in the same vector
index produces meaningless nearest-neighbor results -- this script exists
so the whole index is generated by one consistent method.

Real schema (from db/schema.sql):
  runbooks(runbook_id, title, service_name, content, embedding VECTOR(384), source_s3_key, created_at)
  postmortems(postmortem_id, incident_id, summary, root_cause, remediation_taken, content, embedding VECTOR(384), created_at)

Usage:
  DATABASE_URL="postgresql://..." python agents/reembed_runbooks.py
"""

import asyncio
import os

import asyncpg
from fastembed import TextEmbedding

# Same model name as before -- only the execution engine changes (ONNX
# instead of torch), so this is the closest thing to an apples-to-apples
# swap available.
MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
DATABASE_URL = os.environ["DATABASE_URL"]


def _postmortem_text(row: asyncpg.Record) -> str:
    """Concatenate the text fields that should drive semantic search for
    postmortems -- matches the content construction in postmortem_node."""
    parts = [row.get("summary") or "", row.get("root_cause") or "", row.get("remediation_taken") or ""]
    return "\n".join(p for p in parts if p)


async def reembed_table(conn, embedder: TextEmbedding, table: str, text_fn, id_col: str = "runbook_id") -> None:
    rows = await conn.fetch(f"SELECT * FROM {table}")
    print(f"{table}: {len(rows)} rows found")
    updated = 0
    for row in rows:
        text = text_fn(row)
        if not text.strip():
            print(f"  skipping {table}.{row[id_col]} -- no text to embed")
            continue
        vector = list(embedder.embed([text]))[0].tolist()
        await conn.execute(
            f"UPDATE {table} SET embedding = $1 WHERE {id_col} = $2",
            str(vector),
            row[id_col],
        )
        updated += 1
    print(f"{table}: {updated} rows re-embedded")


async def main() -> None:
    print(f"Loading {MODEL_NAME} via fastembed (ONNX, no torch)...")
    embedder = TextEmbedding(model_name=MODEL_NAME)

    conn = await asyncpg.connect(DATABASE_URL)
    try:
        await reembed_table(conn, embedder, "runbooks", lambda r: r.get("content") or "")
        await reembed_table(conn, embedder, "postmortems", _postmortem_text, id_col="postmortem_id")
    finally:
        await conn.close()

    print(
        "\nDone. Before trusting this in the live demo: run a manual "
        "SELECT ... ORDER BY embedding <-> <query_vector> LIMIT 3 against a "
        "known-similar pair (e.g. the 'payment gateway timeout' vs "
        "'connection pool exhaustion' runbooks) and confirm they still rank "
        "near each other."
    )


if __name__ == "__main__":
    asyncio.run(main())